#!/usr/bin/env python3
"""
Generate sites list for Google Custom Search Engine
"""

def generate_cse_sites():
    """Generate sites in the exact format needed for Google CSE"""
    
    # Top priority sites for historical figures (museums, educational, art)
    priority_sites = [
        # Museums & Cultural (Best for portraits and artifacts)
        "metmuseum.org",
        "britishmuseum.org", 
        "louvre.fr",
        "nationalgallery.org.uk",
        "tate.org.uk",
        "moma.org",
        "getty.edu",
        "clevelandart.org",
        "artic.edu",
        "philamuseum.org",
        "brooklynmuseum.org",
        "nga.gov",
        "centrepompidou.fr",
        "museoreinasofia.es",
        "museothyssen.org",
        "prado.es",
        "museodelprado.es",
        "museobilbao.com",
        "guggenheim-bilbao.eus",
        
        # Educational & Research (Academic sources)
        "harvard.edu",
        "stanford.edu", 
        "mit.edu",
        "princeton.edu",
        "yale.edu",
        "columbia.edu",
        "berkeley.edu",
        "oxford.ac.uk",
        "cambridge.org",
        "ucl.ac.uk",
        "lse.ac.uk",
        "imperial.ac.uk",
        "kcl.ac.uk",
        "ed.ac.uk",
        "manchester.ac.uk",
        "bristol.ac.uk",
        "warwick.ac.uk",
        "durham.ac.uk",
        "exeter.ac.uk",
        "leeds.ac.uk",
        "sheffield.ac.uk",
        "birmingham.ac.uk",
        "nottingham.ac.uk",
        "liverpool.ac.uk",
        "newcastle.ac.uk",
        "cardiff.ac.uk",
        "glasgow.ac.uk",
        "aberdeen.ac.uk",
        "dundee.ac.uk",
        "st-andrews.ac.uk",
        
        # Art & Portrait Sites
        "artcyclopedia.com",
        "artnet.com",
        "artprice.com",
        "christies.com",
        "sothebys.com",
        "bonhams.com",
        "phillips.com",
        "artforum.com",
        "artnews.com",
        "hyperallergic.com",
        "artsy.net",
        "artspace.com",
        "saatchiart.com",
        "behance.net",
        "deviantart.com",
        "pinterest.com",
        "flickr.com",
        "500px.com",
        "unsplash.com",
        "pexels.com",
        "shutterstock.com",
        "istockphoto.com",
        "alamy.com",
        "gettyimages.com",
        "reuters.com",
        "apimages.com",
        "epa.eu",
        "afp.com",
        "bloomberg.com",
        "forbes.com",
        "fortune.com",
        
        # Science & Technology (For achievements and inventions)
        "nature.com",
        "science.org",
        "cell.com",
        "thelancet.com",
        "nejm.org",
        "jama.com",
        "bmj.com",
        "plos.org",
        "arxiv.org",
        "biorxiv.org",
        "medrxiv.org",
        "researchgate.net",
        "academia.edu",
        "scholar.google.com",
        "ieee.org",
        "acm.org",
        "springer.com",
        "elsevier.com",
        "wiley.com",
        "sage.com",
        "tandfonline.com",
        "jstor.org",
        "projecteuclid.org",
        "ams.org",
        "maa.org",
        "mathworld.wolfram.com",
        "wolframalpha.com",
        "mathoverflow.net",
        "stackoverflow.com",
        "github.com",
        "gitlab.com",
        
        # Historical & Biographical
        "biography.com",
        "history.com",
        "britannica.com",
        "encyclopedia.com",
        "infoplease.com",
        "factmonster.com",
        "worldbook.com",
        "collinsdictionary.com",
        "merriam-webster.com",
        "dictionary.com",
        "thesaurus.com",
        "etymonline.com",
        "ancestry.com",
        "familysearch.org",
        "genealogy.com",
        "rootsweb.com",
        "myheritage.com",
        "23andme.com",
        "ancestrydna.com",
        "familytreedna.com",
        
        # Achievement & Award Sites
        "nobelprize.org",
        "pulitzer.org",
        "oscars.org",
        "grammy.com",
        "tonyawards.com",
        "emmys.com",
        "goldenglobes.com",
        "bafta.org",
        "canne.org",
        "berlinale.de",
        "venicebiennale.org",
        "documenta.de",
        "whitney.org",
        "guggenheim.org",
        
        # Invention & Patent Sites
        "uspto.gov",
        "epo.org",
        "wipo.int",
        "google.com/patents",
        "patents.google.com",
        "espacenet.com",
        "patentscope.wipo.int",
        
        # Government & Official (For official records)
        "whitehouse.gov",
        "congress.gov",
        "senate.gov",
        "house.gov",
        "supremecourt.gov",
        "fbi.gov",
        "cia.gov",
        "nsa.gov",
        "dhs.gov",
        "state.gov",
        "defense.gov",
        "energy.gov",
        "nasa.gov",
        "nih.gov",
        "nsf.gov",
        "noaa.gov",
        "usgs.gov",
        "cdc.gov",
        "fda.gov",
        "epa.gov",
        "irs.gov",
        "ssa.gov",
        "va.gov",
        "usaid.gov",
        "peacecorps.gov",
        "uscis.gov",
        "ice.gov",
        "cbp.gov",
        "tsa.gov",
        "fema.gov",
        "usps.com",
        
        # International Organizations
        "un.org",
        "unesco.org",
        "who.int",
        "imf.org",
        "worldbank.org",
        "wto.org",
        "oecd.org",
        "g20.org",
        "g7.org",
        "nato.int",
        "eu.europa.eu",
        "coe.int",
        "osce.org",
        "oas.org",
        "au.int",
        "asean.org",
        "saarc-sec.org",
        "gcc-sg.org",
        "alecso.org",
        "islamic-conference.org",
        "arab-league.org",
        "african-union.org",
        "caricom.org",
        "sadc.int",
        "eac.int",
        "igad.int",
        "comesa.int",
        "ecowas.int",
        
        # News & Media (For current information)
        "reuters.com",
        "ap.org",
        "bloomberg.com",
        "cnn.com",
        "bbc.com",
        "nbc.com",
        "abc.com",
        "cbs.com",
        "fox.com",
        "msnbc.com",
        "cnbc.com",
        "foxbusiness.com",
        "marketwatch.com",
        "wsj.com",
        "ft.com",
        "economist.com",
        "time.com",
        "newsweek.com",
        "usatoday.com",
        "latimes.com",
        "nytimes.com",
        "washingtonpost.com",
        "bostonglobe.com",
        "chicagotribune.com",
        "dallasnews.com",
        "houstonchronicle.com",
        "miamiherald.com",
        "orlandosentinel.com",
        
        # Cultural & Entertainment
        "imdb.com",
        "rottentomatoes.com",
        "metacritic.com",
        "boxofficemojo.com",
        "the-numbers.com",
        "variety.com",
        "hollywoodreporter.com",
        "deadline.com",
        "indiewire.com",
        "screenrant.com",
        "collider.com",
        "slashfilm.com",
        "avclub.com",
        "pitchfork.com",
        "rollingstone.com",
        "billboard.com",
        
        # Sports & Achievement
        "olympics.com",
        "fifa.com",
        "uefa.com",
        "nba.com",
        "nfl.com",
        "mlb.com",
        "nhl.com",
        "mls.com",
        "nascar.com",
        "formula1.com",
        "wwe.com",
        "ufc.com",
        "espn.com",
        "sportsillustrated.com",
        "sportingnews.com",
        "bleacherreport.com",
        "sbnation.com",
        "deadspin.com",
        "theathletic.com",
        "stadium.com",
        
        # Library & Archive Sites
        "loc.gov",
        "archives.gov",
        "nara.gov",
        "digital.library.upenn.edu",
        "bpl.org",
        "nypl.org",
        "lapl.org",
        "sfpl.org",
        "chicagopubliclibrary.org",
        "bostonpubliclibrary.org",
        "seattlepubliclibrary.org",
        "denverlibrary.org",
        "phoenixpubliclibrary.org",
        "dallaslibrary.org",
        "houstonlibrary.org",
        "austinlibrary.org",
        "sanantonio.gov/library",
        "fortworthlibrary.org",
        "arlingtonlibrary.org",
        "plano.gov/library",
        "irvinglibrary.org",
        "garlandtx.gov/library",
        "mckinneytexas.org/library",
        "friscolibrary.com",
        "allenlibrary.org",
        
        # Wikipedia and Wikimedia (Comprehensive coverage)
        "wikipedia.org",
        "wikimedia.org",
        
        # Creative Commons & Open Source
        "creativecommons.org",
        "opensource.org",
        "gnu.org",
        "fsf.org",
        "apache.org",
        "eclipse.org",
        "mozilla.org",
        "webkit.org",
        "blink.org",
        "gecko.org",
        "servo.org",
        "rust-lang.org",
        "python.org",
        "perl.org",
        "ruby-lang.org",
        "php.net",
        "nodejs.org",
        "deno.land",
        "bun.sh",
        "go.dev",
        "golang.org",
        "swift.org",
        "kotlinlang.org",
        "scala-lang.org",
        "clojure.org",
        "haskell.org",
        "ocaml.org",
        "fsharp.org",
        "erlang.org",
        "elixir-lang.org",
        
        # Reference & Documentation
        "docs.python.org",
        "docs.oracle.com",
        "docs.microsoft.com",
        "developer.apple.com",
        "developer.android.com",
        "developer.mozilla.org",
        "docs.github.com",
        "git-scm.com",
        "docker.com/docs",
        "kubernetes.io/docs",
        "helm.sh/docs",
        "terraform.io/docs",
        "ansible.com/docs",
        "puppet.com/docs",
        "chef.io/docs",
        "saltstack.com/docs",
        "consul.io/docs",
        "vaultproject.io/docs",
        "nomadproject.io/docs",
        "packer.io/docs",
        "vagrantup.com/docs",
        "virtualbox.org/wiki",
        "vmware.com/support",
        "parallels.com/support",
        "citrix.com/support",
        "nutanix.com/support",
        "dell.com/support",
        "hp.com/support",
        "lenovo.com/support",
        "asus.com/support",
        "acer.com/support",
        
        # Search & Discovery
        "google.com",
        "bing.com",
        "yahoo.com",
        "duckduckgo.com",
        "startpage.com",
        "searx.me",
        "qwant.com",
        "ecosia.org",
        "brave.com",
        "opera.com",
        "vivaldi.com",
        "firefox.com",
        "chrome.google.com",
        "edge.microsoft.com",
        "safari.apple.com",
        
        # Data & Analytics
        "kaggle.com",
        "data.world",
        "data.gov",
        "data.gov.uk",
        "data.gouv.fr",
        "data.gov.au",
        "data.govt.nz",
        "data.gov.sg",
        "data.gov.hk",
        "data.gov.tw",
        "data.gov.kr",
        "data.gov.jp",
        "data.gov.in",
        "data.gov.br",
        "data.gov.mx",
        "data.gov.ar",
        "data.gov.cl",
        "data.gov.co",
        "data.gov.pe",
        "data.gov.uy",
        "data.gov.py",
        "data.gov.bo",
        "data.gov.ec",
        "data.gov.ve",
        "data.gov.gt",
        "data.gov.hn",
        "data.gov.sv",
        "data.gov.ni",
        "data.gov.cr",
        "data.gov.pa",
        "data.gov.do"
    ]
    
    return priority_sites

def main():
    """Main function to generate CSE sites list"""
    print("🔧 Google Custom Search Engine Sites Generator")
    print("=" * 50)
    print("")
    
    sites = generate_cse_sites()
    
    print(f"📊 Generated {len(sites)} sites for Google CSE")
    print("")
    print("📋 Instructions:")
    print("1. Go to https://cse.google.com/")
    print("2. Select your Custom Search Engine")
    print("3. Go to 'Sites to search' section")
    print("4. Copy and paste the sites below (one per line)")
    print("")
    print("🎯 SITES TO ADD:")
    print("=" * 30)
    print("")
    
    # Print sites in the exact format needed for Google CSE
    for i, site in enumerate(sites, 1):
        print(f"{site}")
    
    print("")
    print("💡 TIPS:")
    print("- Add sites in batches of 20-30 to test performance")
    print("- Start with museums and educational sites first")
    print("- Monitor search result quality")
    print("- Remove low-performing sites if needed")
    print("")
    print(f"✅ Total sites ready to add: {len(sites)}")

if __name__ == "__main__":
    main() 