name: Full System Deployment

on:
  push:
    branches: [ main ]
    paths: [ 'components/**', 'backend/**', 'scripts/**', '.github/workflows/deploy-full.yml' ]
  workflow_dispatch:

env:
  FRONTEND_RESOURCE_GROUP: orb-game-rg-eastus2
  BACKEND_RESOURCE_GROUP: orb-game-rg-eastus2
  CONTAINER_APP_NAME: orb-game-backend-eastus2
  CONTAINER_REGISTRY: orbgameregistry
  IMAGE_NAME: orb-game-backend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ env.CONTAINER_REGISTRY }}
        
    - name: Build and push container image
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --tag ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --tag ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest \
          --file backend/backend-Dockerfile \
          --push \
          ./backend
          
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.BACKEND_RESOURCE_GROUP }} \
          --image ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --set-env-vars \
            AZURE_OPENAI_ENDPOINT="https://aimcs-foundry.cognitiveservices.azure.com/" \
            AZURE_OPENAI_API_KEY="${{ secrets.AZURE_OPENAI_API_KEY }}" \
            AZURE_OPENAI_DEPLOYMENT="${{ secrets.AZURE_OPENAI_DEPLOYMENT }}" \
            AZURE_OPENAI_TTS_DEPLOYMENT="${{ secrets.AZURE_OPENAI_TTS_DEPLOYMENT }}" \
            PERPLEXITY_API_KEY="${{ secrets.PERPLEXITY_API_KEY }}" \
            MONGO_URI="${{ secrets.MONGO_URI }}"
            
    - name: Wait for backend deployment
      run: |
        echo "Waiting for backend deployment to complete..."
        sleep 90
        
    - name: Verify backend health
      run: |
        for i in {1..10}; do
          echo "Attempt $i: Testing backend health..."
          if curl -f https://api.orbgame.us/health; then
            echo "✅ Backend is healthy!"
            break
          else
            echo "❌ Backend not responding, waiting..."
            sleep 30
          fi
        done
        
        curl -f https://api.orbgame.us/health || exit 1

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    name: Deploy Frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Build frontend
      run: |
        npm run build
        
    - name: Zip build output
      run: |
        cd dist
        zip -r ../dist.zip .
        cd ..
        
    - name: Verify build output
      run: |
        ls -la dist/
        test -f dist/index.html || exit 1
        test -f dist.zip || exit 1
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      run: |
        # Deploy to Azure Web App
        az webapp deployment source config-zip \
          --resource-group ${{ env.FRONTEND_RESOURCE_GROUP }} \
          --name orb-game \
          --src dist.zip
        
        # Restart the web app to ensure changes propagate
        echo "🔄 Restarting web app to ensure changes propagate..."
        az webapp restart --name orb-game --resource-group ${{ env.FRONTEND_RESOURCE_GROUP }}
        
        # Clear any cached content
        echo "🧹 Clearing cached content..."
        az webapp config appsettings set --name orb-game --resource-group ${{ env.FRONTEND_RESOURCE_GROUP }} --settings WEBSITE_DYNAMIC_CACHE=0
        az webapp config appsettings set --name orb-game --resource-group ${{ env.FRONTEND_RESOURCE_GROUP }} --settings WEBSITE_DYNAMIC_CACHE=1
        
    - name: Wait for frontend deployment
      timeout-minutes: 10
      run: |
        echo "Waiting for frontend deployment to complete..."
        sleep 180
        
    - name: Verify frontend deployment
      timeout-minutes: 15
      run: |
        echo "Verifying frontend deployment..."
        
        # Get Web App URL
        WEB_APP_URL=$(az webapp show --name orb-game --resource-group ${{ env.FRONTEND_RESOURCE_GROUP }} --query "defaultHostName" --output tsv)
        echo "🌐 Web App URL: https://$WEB_APP_URL"
        
        # Check if the site is serving our content with more attempts and longer waits
        for i in {1..10}; do
          echo "Attempt $i/10: Checking frontend content..."
          RESPONSE=$(curl -s --max-time 30 https://$WEB_APP_URL)
          
          # Check for multiple indicators of our content
          if echo "$RESPONSE" | grep -q "Orb Game" || \
             echo "$RESPONSE" | grep -q "orbgame" || \
             echo "$RESPONSE" | grep -q "AI Multimodal Gaming System" || \
             echo "$RESPONSE" | grep -q "main.jsx" || \
             echo "$RESPONSE" | grep -q "favicon.svg"; then
            echo "✅ Frontend is serving our content!"
            break
          else
            echo "❓ Unknown response, waiting 60 seconds..."
            echo "Response preview:"
            echo "$RESPONSE" | head -15
            sleep 60
          fi
        done
        
        # Final verification with more detailed output
        echo "🔍 Final verification..."
        FINAL_RESPONSE=$(curl -s --max-time 30 https://$WEB_APP_URL)
        
        # Check for multiple indicators of our content
        if echo "$FINAL_RESPONSE" | grep -q "Orb Game" || \
           echo "$FINAL_RESPONSE" | grep -q "orbgame" || \
           echo "$FINAL_RESPONSE" | grep -q "AI Multimodal Gaming System" || \
           echo "$FINAL_RESPONSE" | grep -q "main.jsx" || \
           echo "$FINAL_RESPONSE" | grep -q "favicon.svg"; then
          echo "✅ Frontend deployment verified!"
          echo "📄 Content indicators found:"
          echo "$FINAL_RESPONSE" | grep -E "(Orb Game|orbgame|AI Multimodal Gaming System|main.jsx|favicon.svg)" | head -5
        else
          echo "❌ Frontend deployment verification failed"
          echo "📄 Full response for debugging:"
          echo "$FINAL_RESPONSE" | head -30
          echo "🔍 Checking if site is accessible at all..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://$WEB_APP_URL)
          echo "HTTP Status: $HTTP_STATUS"
          echo "🔍 Checking for any HTML content..."
          if echo "$FINAL_RESPONSE" | grep -q "<!doctype html\|<html\|<head\|<body"; then
            echo "✅ HTML structure detected, but missing expected content"
          else
            echo "❌ No HTML structure detected"
          fi
          exit 1
        fi

  system-test:
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    name: System Integration Test
    
    steps:
    - name: Test frontend accessibility
      timeout-minutes: 5
      run: |
        echo "Testing frontend..."
        curl -f https://orbgame.us || exit 1
        
    - name: Test backend API
      timeout-minutes: 5
      run: |
        echo "Testing backend API..."
        curl -f https://api.orbgame.us/health || exit 1
        
    - name: Test full chat flow
      timeout-minutes: 10
      run: |
        echo "Testing complete chat flow..."
        
        # Test chat endpoint
        RESPONSE=$(curl -s -X POST https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/api/chat \
          -H "Content-Type: application/json" \
          -d '{"message": "Hello, this is a deployment test"}')
          
        if echo "$RESPONSE" | grep -q "response"; then
          echo "✅ Chat API working correctly"
        else
          echo "❌ Chat API failed"
          echo "Response: $RESPONSE"
          exit 1
        fi
        
    - name: Test web search functionality
      timeout-minutes: 10
      run: |
        echo "Testing web search..."
        
        RESPONSE=$(curl -s -X POST https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/api/chat \
          -H "Content-Type: application/json" \
          -d '{"message": "What is the latest news today?", "useWebSearch": "auto"}')
          
        if echo "$RESPONSE" | grep -q "response"; then
          echo "✅ Web search working correctly"
        else
          echo "❌ Web search failed"
          echo "Response: $RESPONSE"
          exit 1
        fi
        
    - name: Test memory system functionality
      timeout-minutes: 15
      run: |
        echo "Testing memory system..."
        
        # Test memory statistics endpoint with retry logic
        echo "🧪 Testing memory stats endpoint with retry logic..."
        MEMORY_STATS=""
        for i in {1..5}; do
          echo "Attempt $i/5: Testing memory stats endpoint..."
          MEMORY_STATS=$(curl -s --max-time 30 https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/api/memory/stats)
          
          if echo "$MEMORY_STATS" | grep -q "totalMemories"; then
            echo "✅ Memory stats endpoint working on attempt $i"
            break
          else
            echo "❌ Memory stats endpoint failed on attempt $i"
            echo "Response: $MEMORY_STATS"
            if [ $i -lt 5 ]; then
              echo "⏳ Waiting 30 seconds before retry..."
              sleep 30
            fi
          fi
        done
        
        if ! echo "$MEMORY_STATS" | grep -q "totalMemories"; then
          echo "❌ Memory stats endpoint failed after all retries"
          echo "Final response: $MEMORY_STATS"
          echo "🔍 Checking if backend is accessible..."
          BACKEND_HEALTH=$(curl -s --max-time 10 https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/health)
          echo "Backend health: $BACKEND_HEALTH"
          echo "⚠️ Memory service may not be initialized - continuing with other tests"
        else
          echo "✅ Memory stats endpoint working correctly"
        fi
        
        # Test memory search endpoint with retry logic
        echo "🧪 Testing memory search endpoint with retry logic..."
        MEMORY_SEARCH=""
        for i in {1..3}; do
          echo "Attempt $i/3: Testing memory search endpoint..."
          MEMORY_SEARCH=$(curl -s --max-time 30 -X POST https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/api/memory/search \
            -H "Content-Type: application/json" \
            -d '{"query": "test", "userId": "deployment-test"}')
          
          if echo "$MEMORY_SEARCH" | grep -q "memories"; then
            echo "✅ Memory search endpoint working on attempt $i"
            break
          else
            echo "❌ Memory search endpoint failed on attempt $i"
            echo "Response: $MEMORY_SEARCH"
            if [ $i -lt 3 ]; then
              echo "⏳ Waiting 20 seconds before retry..."
              sleep 20
            fi
          fi
        done
        
        if ! echo "$MEMORY_SEARCH" | grep -q "memories"; then
          echo "❌ Memory search endpoint failed after all retries"
          echo "Final response: $MEMORY_SEARCH"
          echo "⚠️ Memory search may not be available - continuing with other tests"
        else
          echo "✅ Memory search endpoint working correctly"
        fi
        
        # Test memory caching (send same message twice) with retry logic
        echo "🧪 Testing memory caching with retry logic..."
        FIRST_RESPONSE=""
        SECOND_RESPONSE=""
        
        for i in {1..3}; do
          echo "Attempt $i/3: Testing memory caching..."
          FIRST_RESPONSE=$(curl -s --max-time 30 -X POST https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/api/chat \
            -H "Content-Type: application/json" \
            -d '{"message": "Memory test question", "userId": "deployment-test"}')
          
          if echo "$FIRST_RESPONSE" | grep -q "response"; then
            echo "✅ First chat request successful on attempt $i"
            break
          else
            echo "❌ First chat request failed on attempt $i"
            echo "Response: $FIRST_RESPONSE"
            if [ $i -lt 3 ]; then
              echo "⏳ Waiting 20 seconds before retry..."
              sleep 20
            fi
          fi
        done
        
        if echo "$FIRST_RESPONSE" | grep -q "response"; then
          echo "✅ First chat request successful"
          
          # Wait a moment before second request
          sleep 10
          
          SECOND_RESPONSE=$(curl -s --max-time 30 -X POST https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io/api/chat \
            -H "Content-Type: application/json" \
            -d '{"message": "Memory test question", "userId": "deployment-test"}')
          
          if echo "$SECOND_RESPONSE" | grep -q "fromMemory.*true"; then
            echo "✅ Memory caching working correctly"
          else
            echo "⚠️ Memory caching not detected (may be first run or memory service unavailable)"
            echo "Second response: $SECOND_RESPONSE"
          fi
        else
          echo "❌ Chat request failed after all retries"
          echo "Final response: $FIRST_RESPONSE"
        fi
        
        echo "🧠 Memory system test completed"

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend, system-test]
    if: always()
    name: Deployment Summary
    
    steps:
    - name: Deployment status
      run: |
        if [ ${{ needs.deploy-backend.result }} == 'success' ] && \
           [ ${{ needs.deploy-frontend.result }} == 'success' ] && \
           [ ${{ needs.system-test.result }} == 'success' ]; then
          echo "🎉 Full deployment successful!"
          echo "Frontend: https://orb-game.azurewebsites.net"
          echo "Backend: https://orb-game-backend-eastus2.gentleglacier-6f66d2ea.eastus2.azurecontainerapps.io"
          echo "Memory System: ✅ Active"
          echo "Memory Panel: 🧠 Available in UI"
          echo "Memory API: /api/memory/* endpoints"
          echo "Commit: ${{ github.sha }}"
        else
          echo "❌ Deployment failed!"
          echo "Backend: ${{ needs.deploy-backend.result }}"
          echo "Frontend: ${{ needs.deploy-frontend.result }}"
          echo "System Test: ${{ needs.system-test.result }}"
          exit 1
        fi 